# wiki/_config.yml

logo: "/assets/images/lug_logo_finished_by_polymachairoplacida.png"
title: Star Citizen LUG Wiki
description: The Star Citizen Linux Users Group Wiki. Everything you need to know to run Star Citizen on Linux!
baseurl: ""
permalink: /:path
include:
  - "*.md"

remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-github-metadata
  - jekyll-include-cache

just_the_docs:
  custom_css:
    - custom

search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: true

nav_sort: case_insensitive

aux_links:
  "ğŸ“š Contribute to this wiki":
    - "https://github.com/starcitizen-lug/knowledge-base"

nav_external_links:
  - title: ğŸ§ Join our Org!
    url: https://robertsspaceindustries.com/orgs/LUG
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: true # set to true to open this link in a new tab - defaults to false
  - title: ğŸ—¨ Discord
    url: https://discord.gg/meCFYPj
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: true # set to true to open this link in a new tab - defaults to false
  - title: ğŸ˜ Matrix space
    url: https://matrix.to/#/#SCLUG:matrix.org
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: true # set to true to open this link in a new tab - defaults to false

color_scheme: dark

callouts:
  note:
    title: Note
    color: blue
  tip:
    title: Tip
    color: green
  important:
    title: Important
    color: purple
  warning:
    title: Warning
    color: yellow
  caution:
    title: Caution
    color: red